name: Update Known Hallucinations

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update_known_hallucinations:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch PR message content
        id: pr_message
        uses: actions/github-script@v5
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return pr.data.body;

      - name: Update hallucinations.json
        run: |
          export PR_MESSAGE="${{ steps.pr_message.outputs.result }}"
          python scripts/update_hallucinations.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"
          git add known_hallucinations.json
          git commit -m "Update known_hallucinations.json [skip ci]"
          git push
